import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { CONFIG_DIR } from "../config.ts";

export const CLOUDFLARED_DIR = join(CONFIG_DIR, "cloudflared");

export const DEFAULT_TUNNEL_NAME = "parachute";

/**
 * Per-tunnel config + log file paths. Each tunnel gets its own subdirectory
 * under `~/.parachute/cloudflared/<tunnelName>/` so multiple tunnels on one
 * box don't trample each other's config.yml or interleave log lines.
 *
 * The default tunnel ("parachute") lives at
 * `~/.parachute/cloudflared/parachute/{config.yml,cloudflared.log}` — a
 * location change from pre-#32 (`~/.parachute/cloudflared/config.yml`).
 * Re-running `parachute expose public --cloudflare` regenerates the file
 * at the new path; the legacy file is left in place but unused.
 */
export function cloudflaredPathsFor(tunnelName: string): {
  configPath: string;
  logPath: string;
} {
  const dir = join(CLOUDFLARED_DIR, tunnelName);
  return {
    configPath: join(dir, "config.yml"),
    logPath: join(dir, "cloudflared.log"),
  };
}

export interface TunnelConfigOpts {
  tunnelUuid: string;
  /** Absolute path to the per-tunnel credentials JSON (`~/.cloudflared/<uuid>.json`). */
  credentialsFile: string;
  hostname: string;
  /** Loopback port the tunnel forwards traffic to (vault = 1940). */
  servicePort: number;
}

/**
 * Emit a cloudflared config.yml. The shape is pinned to the documented
 * Named Tunnel + ingress rules schema; we route every request for the
 * configured hostname to the local service port and 404 everything else.
 *
 * Single-hostname ingress today. Multi-service routing (hub at /, vault
 * under /vault/…, etc.) is deferred — the hub/OAuth seam lives on the
 * Tailscale Funnel path and wasn't worth duplicating into the Cloudflare
 * shape before we have a second CF user pushing on it.
 */
/**
 * Double-quote `credentials-file` so a `$HOME` with a space (e.g. macOS
 * "John Doe") doesn't break YAML parsing. Tunnel UUIDs and `http://localhost`
 * URLs don't need quoting by the YAML spec, so only this one path gets it.
 * Backslashes and double-quotes inside the path are escaped.
 */
function yamlQuote(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

export function renderConfig(opts: TunnelConfigOpts): string {
  return `# Generated by parachute expose public --cloudflare — do not edit by hand.
# Re-running the command regenerates this file.
tunnel: ${opts.tunnelUuid}
credentials-file: ${yamlQuote(opts.credentialsFile)}

ingress:
  - hostname: ${opts.hostname}
    service: http://localhost:${opts.servicePort}
  - service: http_status:404
`;
}

export function writeConfig(opts: TunnelConfigOpts, configPath: string): string {
  mkdirSync(dirname(configPath), { recursive: true });
  writeFileSync(configPath, renderConfig(opts));
  return configPath;
}
