import {
  type ManagedUnit,
  type ManagedUnitDeps,
  type ManagedUnitInstallResult,
  type ManagedUnitMessages,
  type ManagedUnitRemoveResult,
  type ServiceCommandResult,
  defaultManagedUnitDeps,
  installManagedUnit,
  launchdPlistPathForLabel,
  removeManagedUnit,
  renderManagedLaunchdPlist,
  renderManagedSystemdUnit,
  systemdUnitPathForName,
} from "../managed-unit.ts";

/**
 * Reboot-persistent cloudflared connector.
 *
 * Pre-0.6.2 `parachute expose public --cloudflare` spawned the connector as a
 * bare detached background process (`Bun.spawn(...).unref()`), which dies on
 * reboot — the operator had to re-run the expose command every time the box
 * restarted. This module installs a per-tunnel OS service that runs the same
 * `cloudflared tunnel --config <path> run` command on boot, so the connector
 * survives reboots.
 *
 * Platform shapes:
 *   - macOS  → a launchd LaunchAgent plist at
 *     `~/Library/LaunchAgents/computer.parachute.cloudflared.<tunnelName>.plist`
 *     (RunAtLoad + KeepAlive), bootstrapped into the per-user GUI domain. No
 *     sudo: a LaunchAgent runs as the logged-in user.
 *   - Linux (non-root) → a systemd *user* unit at
 *     `~/.config/systemd/user/parachute-cloudflared-<tunnelName>.service`,
 *     `systemctl --user enable --now`, plus a best-effort
 *     `loginctl enable-linger $USER` so the unit runs without an active login.
 *   - Linux (root) → a systemd *system* unit at
 *     `/etc/systemd/system/parachute-cloudflared-<tunnelName>.service`,
 *     `systemctl enable --now`. No linger needed — system units run on boot.
 *
 * As of Phase 2b of the hub-as-supervisor unification, the per-platform
 * install/remove/render machinery lives in `src/managed-unit.ts` as a reusable
 * `ManagedUnit` abstraction (so the hub unit can reuse it — design §4.1). This
 * module is now a thin connector-specific layer over that machinery: it builds
 * the connector's `ManagedUnit` descriptor (empty env, no crash-loop ceiling —
 * which keeps its rendered output BYTE-IDENTICAL to the pre-extraction code, the
 * hard constraint since the connector is live on production) and supplies the
 * connector-flavored install/remove messages. The public exports below keep
 * their original signatures so `expose-cloudflare.ts` and the connector tests
 * need no behavioral change.
 *
 * Everything is behind an injectable deps seam (re-exported `ConnectorServiceDeps`
 * = the generalized `ManagedUnitDeps`) so tests drive the install/remove without
 * touching real launchctl/systemctl or the operator's home directory.
 *
 * Service name keyed by the same per-host tunnel name the 0.6.1 work derives
 * (`deriveTunnelName`), so install / remove always target the connector for
 * exactly one tunnel and the expose off / legacy-sweep paths can tear it down.
 */

/** Synchronous command result from the injected service runner. */
export type { ServiceCommandResult };

/**
 * Injectable side-effect seam for the connector-service module. This is the
 * generalized `ManagedUnitDeps` re-exported under the connector's historical
 * name so `expose-cloudflare.ts` + the connector tests are unchanged.
 */
export type ConnectorServiceDeps = ManagedUnitDeps;

export const defaultServiceDeps: ConnectorServiceDeps = defaultManagedUnitDeps;

/** Reverse-DNS prefix for the launchd label + plist filename. */
const LAUNCHD_LABEL_PREFIX = "computer.parachute.cloudflared";
/** systemd unit name prefix. */
const SYSTEMD_UNIT_PREFIX = "parachute-cloudflared-";
/** Provenance comment baked into every rendered connector unit file. */
const CONNECTOR_HEADER = "Generated by parachute expose public --cloudflare — do not edit by hand.";

/** launchd label for a tunnel (also the plist basename, minus `.plist`). */
export function launchdLabel(tunnelName: string): string {
  return `${LAUNCHD_LABEL_PREFIX}.${tunnelName}`;
}

/** launchd plist path under the user's LaunchAgents dir. */
export function launchdPlistPath(tunnelName: string, home: string): string {
  return launchdPlistPathForLabel(launchdLabel(tunnelName), home);
}

/** systemd unit name (with `.service` suffix). */
export function systemdUnitName(tunnelName: string): string {
  return `${SYSTEMD_UNIT_PREFIX}${tunnelName}.service`;
}

/** systemd unit path — user-level under $HOME, system-level under /etc. */
export function systemdUnitPath(tunnelName: string, home: string, root: boolean): string {
  return systemdUnitPathForName(systemdUnitName(tunnelName), home, root);
}

/**
 * Build the connector's `ManagedUnit` descriptor. Empty `env` + no `crashLoop`
 * are what keep the rendered output byte-identical to the pre-extraction code.
 * `runAsInvokingUserOnSystemUnit: true` reproduces the connector's historical
 * `User=` pin on the root/system unit.
 */
function connectorUnit(opts: {
  tunnelName: string;
  cloudflaredPath: string;
  configPath: string;
  logPath: string;
}): ManagedUnit {
  return {
    launchdLabel: launchdLabel(opts.tunnelName),
    systemdUnitName: systemdUnitName(opts.tunnelName),
    headerComment: CONNECTOR_HEADER,
    systemdDescription: `Parachute Cloudflare connector (${opts.tunnelName})`,
    execStart: [opts.cloudflaredPath, "tunnel", "--config", opts.configPath, "run"],
    env: {},
    logPath: opts.logPath,
    runAsInvokingUserOnSystemUnit: true,
  };
}

/**
 * Render the launchd LaunchAgent plist. Thin wrapper over the generalized
 * renderer with the connector's descriptor — preserved signature so existing
 * callers/tests are unchanged.
 */
export function renderLaunchdPlist(opts: {
  tunnelName: string;
  cloudflaredPath: string;
  configPath: string;
  logPath: string;
}): string {
  return renderManagedLaunchdPlist(connectorUnit(opts));
}

/**
 * Render a systemd unit. Thin wrapper over the generalized renderer — preserved
 * signature (`{ root, userName }` threaded through) so existing callers/tests
 * are unchanged.
 */
export function renderSystemdUnit(opts: {
  tunnelName: string;
  cloudflaredPath: string;
  configPath: string;
  logPath: string;
  root: boolean;
  userName: string;
}): string {
  const { root, userName } = opts;
  return renderManagedSystemdUnit(connectorUnit(opts), { root, userName });
}

export interface InstallResult {
  /**
   * "installed" → an OS service now owns the connector (survives reboot).
   * "fallback" → the service tool was unavailable / failed; the caller should
   * fall back to the transient `proc.unref()` spawn (does NOT survive reboot).
   */
  outcome: "installed" | "fallback";
  /** Which init system installed the service (when outcome === "installed"). */
  kind?: "launchd" | "systemd-user" | "systemd-system" | "unsupported";
  /** Path of the written service file (when outcome === "installed"). */
  servicePath?: string;
  /** Human-readable lines for the CLI to print (warnings, hints). */
  messages: string[];
}

export interface ConnectorServiceOpts {
  tunnelName: string;
  configPath: string;
  logPath: string;
  deps?: ConnectorServiceDeps;
}

/** Connector-flavored install/remove messages, supplied to the generalized installer. */
function connectorMessages(): ManagedUnitMessages {
  const lingerWarning =
    "Note: could not enable lingering (loginctl enable-linger) — the connector will run while you're logged in but may not start on a cold boot before login. To run on cold boot without an active login, re-run this command as root (installs a system unit that needs no linger).";
  return {
    launchctlMissing: "launchctl not found; using a transient connector (won't survive a reboot).",
    systemctlMissing: "systemctl not found; using a transient connector (won't survive a reboot).",
    lingerWarning,
    writeFailedPrefix:
      "Failed to write service file; using a transient connector (won't survive a reboot)",
    launchctlLoadFailedPrefix:
      "launchctl could not load the connector service; using a transient connector (won't survive a reboot)",
    daemonReloadFailedPrefix:
      "systemctl daemon-reload failed; using a transient connector (won't survive a reboot)",
    enableFailedPrefix:
      "systemctl enable --now failed; using a transient connector (won't survive a reboot)",
    // The connector always installs with start:true, so the `started` param these
    // callbacks receive is unused here — the message is always the "starts now" variant.
    launchdInstalled: (label, _started) =>
      `Installed launchd LaunchAgent ${label} — the connector now starts on login/boot.`,
    systemdInstalled: (unitName, root, _started) =>
      `Installed systemd ${root ? "system" : "user"} unit ${unitName} — the connector now starts on boot.`,
  };
}

/**
 * Install (or refresh) the reboot-persistent connector service for one tunnel
 * and start it. Idempotent: re-installing overwrites the service file and
 * re-loads it, so re-`expose` of the same hostname converges on exactly one
 * managed connector.
 *
 * Graceful fallback: if the platform's service tool is missing or any step
 * fails, returns `{ outcome: "fallback", messages }` WITHOUT throwing — the
 * caller then spawns the transient connector and warns it won't survive a
 * reboot. We never hard-fail the expose because the service install didn't take.
 */
export function installConnectorService(opts: ConnectorServiceOpts): InstallResult {
  const deps = opts.deps ?? defaultServiceDeps;
  const cloudflaredPath = deps.which("cloudflared");
  if (!cloudflaredPath) {
    return {
      outcome: "fallback",
      messages: ["Could not resolve the cloudflared binary path; skipping boot-service install."],
    };
  }
  if (deps.platform !== "darwin" && deps.platform !== "linux") {
    return {
      outcome: "fallback",
      messages: [
        `Boot-persistent connector isn't supported on ${deps.platform}; using a transient connector.`,
      ],
    };
  }

  const result: ManagedUnitInstallResult = installManagedUnit({
    unit: connectorUnit({
      tunnelName: opts.tunnelName,
      cloudflaredPath,
      configPath: opts.configPath,
      logPath: opts.logPath,
    }),
    deps,
    messages: connectorMessages(),
    // start: true (default) — the connector's behavior is unchanged.
  });
  return result;
}

export interface RemoveResult {
  /** True when a service file was found + removed (best-effort tool teardown ran). */
  removed: boolean;
  messages: string[];
}

/**
 * Stop + remove the reboot-persistent connector service for one tunnel.
 * Idempotent + best-effort: a missing service file is a no-op; tool failures
 * never throw (the expose-off path must always succeed at clearing state even
 * if the OS service tool hiccups). Mirrors `installConnectorService`'s seam.
 *
 * Called by `exposeCloudflareOff` (and the legacy-tunnel sweep) so tearing down
 * a tunnel also tears down its boot service — otherwise the service would
 * resurrect a dead connector on the next reboot.
 */
export function removeConnectorService(opts: {
  tunnelName: string;
  deps?: ConnectorServiceDeps;
}): RemoveResult {
  const deps = opts.deps ?? defaultServiceDeps;
  const result: ManagedUnitRemoveResult = removeManagedUnit({
    launchdLabel: launchdLabel(opts.tunnelName),
    systemdUnitName: systemdUnitName(opts.tunnelName),
    deps,
    removedLaunchdMessage: (label) => `Removed launchd LaunchAgent ${label}.`,
    removedSystemdMessage: (unitName) => `Removed systemd unit ${unitName}.`,
  });
  return result;
}
